### ISSUE TITLE
Logback: level filtering

### ISSUE THREAD

**Issue by benjyz** [ScorexProject/Scorex-Lagonaki#31]
How about adding back logback.xml? Not sure if this is scala-idiomatic, but logback offers a lot of functionality, such as filtering etc.  

see:
https://github.com/typesafehub/scala-logging

older commit:
https://github.com/ScorexProject/Scorex-Lagonaki/commit/6d86cba402e75c062401b392dcac452f4aeec4c6

**Comment by catena2w** [comment]
it's stille there: https://github.com/ScorexProject/Scorex-Lagonaki/blob/master/src/main/resources/logback.xml

**Comment by benjyz** [comment]
Thanks. I had the impression it gets deleted on recompile but can't replicate.
